<?php

/**
 * @file
 * Defines the core Commerce store entity, including the entity itself
 * and various API functions to managestores and interact with
 * them through forms and autocompletes.
 */

/**
 * Implements hook_menu().
 */
function commerce_store_menu() {
  $items = array();

  $items['commerce_store/autocomplete'] = array(
    'title' => 'commerce_store autocomplete',
    'page callback' => 'commerce_store_autocomplete',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_hook_info().
 */
function commerce_store_hook_info() {
  $hooks = array(
    'commerce_store_uri' => array(
      'group' => 'commerce',
    ),
    'commerce_store_view' => array(
      'group' => 'commerce',
    ),
    'commerce_store_presave' => array(
      'group' => 'commerce',
    ),
    'commerce_store_insert' => array(
      'group' => 'commerce',
    ),
    'commerce_store_update' => array(
      'group' => 'commerce',
    ),
    'commerce_store_can_delete' => array(
      'group' => 'commerce',
    ),
    'commerce_store_delete' => array(
      'group' => 'commerce',
    ),
  );

  return $hooks;
}

/**
 * Implements hook_entity_info().
 */
function commerce_store_entity_info() {
  $return = array(
    'commerce_store' => array(
      'label' => t('Commerce Store'),
      'controller class' => 'CommerceStoreEntityController',
      'base table' => 'commerce_store',
      'revision table' => 'commerce_store_revision',
      'fieldable' => TRUE,
      'entity keys' => array(
        'id' => 'store_id',
        'label' => 'title',
        'revision' => 'revision_id',
      ),
      'bundles' => array(
        'commerce_store' => array(
          'label' => t('Store', array(), array('context' => 'a drupal commerce store')),
        ),
      ),
      'view modes' => array(
        'full' => array(
          'label' => t('Admin display'),
          'custom settings' => FALSE,
        ),
      ),
      'uri callback' => 'commerce_store_uri',
      'metadata controller class' => '',
      'token type' => 'commerce-store',
      'access callback' => 'commerce_entity_access',
      'access arguments' => array(
        'user key' => 'uid',
        'access tag' => 'commerce_store_access',
      ),
      'permission labels' => array(
        'singular' => t('store'),
        'plural' => t('stores'),
      ),

      // Add title replacement support for translations.
      'field replacement' => array(
        'title' => array(
          'field' => array(
            'type' => 'text',
            'cardinality' => 1,
            'translatable' => TRUE,
          ),
          'instance' => array(
            'label' => t('Title'),
            'required' => TRUE,
            'settings' => array(
              'text_processing' => 0,
            ),
            'widget' => array(
              'weight' => -5,
            ),
          ),
        ),
      ),
    ),
  );

  return $return;
}

/**
 * Entity uri callback: gives modules a chance to specify a path for a store.
 */
function commerce_store_uri($store) {
  // Allow modules to specify a path, returning the first one found.
  foreach (module_implements('commerce_store_uri') as $module) {
    $uri = module_invoke($module, 'commerce_store_uri', $store);

    // If the implementation returned data, use that now.
    if (!empty($uri)) {
      return $uri;
    }
  }

  return NULL;
}

/**
 * Implements hook_views_api().
 */
function commerce_store_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'commerce_store') . '/includes/views',
  );
}

/**
 * Implements hook_permission().
 */
function commerce_store_permission() {
  $permissions = array(
    'administer stores' => array(
      'title' => t('Administer Store'),
      'description' => t('Allows users to configure and manage stores.'),
      'restrict access' => TRUE,
    ),
  );

  $permissions += commerce_entity_access_permissions('commerce_store');

  return $permissions;
}

/**
 * Saves a store.
 *
 * @param $store
 *   The full store object to save.
 *
 * @return
 *   SAVED_NEW or SAVED_UPDATED depending on the operation performed.
 */
function commerce_store_save($store) {
  return entity_get_controller('commerce_store')->save($store);
}

/**
 * Loads a store by ID.
 */
function commerce_store_load($store_id) {
  if (empty($store_id)) {
    return FALSE;
  }

  $stores = commerce_store_load_multiple(array($store_id), array());
  return $stores ? reset($stores) : FALSE;
}

/**
 * Loads multiple stores by ID or based on a set of matching conditions.
 *
 * @see entity_load()
 *
 * @param $store_ids
 *   An array of store IDs.
 * @param $conditions
 *   An array of conditions on the {commerce_store} table in the form
 *     'field' => $value.
 * @param $reset
 *   Whether to reset the internal store loading cache.
 *
 * @return
 *   An array of store objects indexed by store_id.
 */
function commerce_store_load_multiple($store_ids = array(), $conditions = array(), $reset = FALSE) {
  if (empty($store_ids) && empty($conditions)) {
    return array();
  }

  return entity_load('commerce_store', $store_ids, $conditions, $reset);
}

/**
 * Determines whether or not the give store can be deleted.
 *
 * @param $store
 *   The store to be checked for deletion.
 *
 * @return
 *   Boolean indicating whether or not the store can be deleted.
 */
function commerce_store_can_delete($store) {
  // Return FALSE if the given store does not have an ID; it need not be
  // deleted, which is functionally equivalent to cannot be deleted as far as
  // code depending on this function is concerned.
  if (empty($store->store_id)) {
    return FALSE;
  }

  // If any module implementing hook_commerce_store_can_delete() returns FALSE
  // the store cannot be deleted. Return TRUE if none return FALSE.
  return !in_array(FALSE, module_invoke_all('commerce_store_can_delete', $store));
}

/**
 * Deletes a store by ID.
 *
 * @param $store_id
 *   The ID of the store to delete.
 *
 * @return
 *   TRUE on success, FALSE otherwise.
 */
function commerce_store_delete($store_id) {
  return commerce_store_delete_multiple(array($store_id));
}

/**
 * Deletes multiple stores by ID.
 *
 * @param $store_ids
 *   An array of store IDs to delete.
 *
 * @return
 *   TRUE on success, FALSE otherwise.
 */
function commerce_store_delete_multiple($store_ids) {
  return entity_get_controller('commerce_store')->delete($store_ids);
}

/**
 * Checks store access for various operations.
 *
 * @param $op
 *   The operation being performed. One of 'view', 'update', 'create' or
 *   'delete'.
 * @param $store
 *   Optionally a store to check access for or for the create operation the
 *   store type. If nothing is given access permissions for all stores are returned.
 * @param $account
 *   The user to check for. Leave it to NULL to check for the current user.
 */
function commerce_store_access($op, $store = NULL, $account = NULL) {
  return commerce_entity_access($op, $store, $account, 'commerce_store');
}

/**
 * Implementation of hook_query_commerce_store_access_alter().
 */
function commerce_store_query_commerce_store_access_alter(QueryAlterableInterface $query) {
  return commerce_entity_access_query_alter($query, 'commerce_store');
}

/**
 * Callback for getting store properties.
 * @see commerce_store_entity_property_info()
 */
function commerce_store_get_properties($store, array $options, $name) {
  switch ($name) {
    case 'creator':
      return $store->uid;
    case 'edit_url':
      return url('admin/commerce/stores/' . $store->store_id . '/edit', $options);
  }
}

/**
 * Callback for setting store properties.
 * @see commerce_store_entity_property_info()
 */
function commerce_store_set_properties($store, $name, $value) {
  if ($name == 'creator') {
    $store->uid = $value;
  }
}

/**
 * Returns output for store autocompletes.
 *
 * The values returned will be keyed by SKU and appear as such in the textfield,
 * even though the preview in the autocomplete list shows "SKU: Title".
 */
function commerce_store_autocomplete($entity_type, $field_name, $bundle, $string = '') {
  $field = field_info_field($field_name);
  $instance = field_info_instance($entity_type, $field_name, $bundle);

  $matches = array();

  // The user enters a comma-separated list of tags. We only autocomplete the last tag.
  $tags_typed = drupal_explode_tags($string);
  $tag_last = drupal_strtolower(array_pop($tags_typed));

  if (!empty($tag_last)) {
    $prefix = count($tags_typed) ? implode(', ', $tags_typed) . ', ' : '';

    // Determine the type of autocomplete match to use when searching for stores.
    $match = isset($field['widget']['autocomplete_match']) ? $field['widget']['autocomplete_match'] : 'contains';

    // Get an array of matching stores.
    $stores = commerce_store_match_stores($field, $instance, $tag_last, $match, array(), 10);

    // Loop through the stores and convert them into autocomplete output.
    foreach ($stores as $store_id => $data) {
      // Add a class wrapper for a few required CSS overrides.
      $matches[$prefix . $data['sku']] = '<div class="reference-autocomplete">' . $data['rendered'] . '</div>';
    }
  }

  drupal_json_output($matches);
}

/**
 * Fetches an array of all stores matching the given parameters.
 *
 * This info is used in various places (allowed values, autocomplete results,
 * input validation...). Some of them only need the store_ids, others
 * store_id + titles, others yet store_id + titles + rendered row (for
 * display in widgets).
 *
 * The array we return contains all the potentially needed information,
 * and lets calling functions use the parts they actually need.
 *
 * @param $field
 *   The field description.
 * @param $string
 *   Optional string to filter SKUs and titles on (used by autocomplete).
 * @param $match
 *   Operator to match filtered SKUs and titles against, can be any of:
 *   'contains', 'equals', 'starts_with'
 * @param $ids
 *   Optional store ids to lookup (used when $string and $match arguments are
 *   not given).
 * @param $limit
 *   If non-zero, limit the size of the result set.
 * @param $access_tag
 *   Boolean indicating whether or not an access control tag should be added to
 *   the query to find matching store data. Defaults to FALSE.
 *
 * @return
 *   An array of valid stores in the form:
 *   array(
 *     store_id => array(
 *       'title' => The store title,
 *       'rendered' => The text to display in widgets (can be HTML)
 *     ),
 *     ...
 *   )
 */
function commerce_store_match_stores($field, $instance = NULL, $string = '', $match = 'contains', $ids = array(), $limit = NULL, $access_tag = FALSE) {
  $results = &drupal_static(__FUNCTION__, array());

  // Create unique id for static cache.
  $cid = implode(':', array(
    $field['field_name'],
    $match,
    ($string !== '' ? $string : implode('-', $ids)),
    $limit,
  ));

  if (!isset($results[$cid])) {
    $matches = _commerce_store_match_stores_standard($instance, $string, $match, $ids, $limit, $access_tag);

    // Store the results.
    $results[$cid] = !empty($matches) ? $matches : array();
  }

  return $results[$cid];
}

/**
 * Helper function for commerce_store_match_stores().
 *
 * Returns an array of stores matching the specific parameters.
 */
function _commerce_store_match_stores_standard($instance, $string = '', $match = 'contains', $ids = array(), $limit = NULL, $access_tag = FALSE) {
  // Build the query object with the necessary fields.
  $query = db_select('commerce_store', 'cp');

  // Add the access control tag if specified.
  if ($access_tag) {
    $query->addTag('commerce_store_access');
  }

  $store_id_alias = $query->addField('cp', 'store_id');
  $store_title_alias = $query->addField('cp', 'title');

  if ($string !== '') {
    $args = array();

    // Build a where clause matching on either the SKU or title.
    switch ($match) {
      case 'contains':
        $where = '(cp.title LIKE :title_match)';
        $args['title_match'] = '%' . $string . '%';
        break;

      case 'starts_with':
        $where = '(cp.title LIKE :title_match)';
        $args['title_match'] = $string . '%';
        break;

      case 'equals':
      default:
        $where = '(cp.title = :title_match)';
        $args['title_match'] = $string;
        break;
    }

    $query->where($where, $args);
  }
  elseif ($ids) {
    // Otherwise add a store_id specific condition if specified.
    $query->condition($store_id_alias, $ids, 'IN', $ids);
  }

  // Order the results by title
  $query
    ->orderBy($store_title_alias);

  // Add a limit if specified.
  if ($limit) {
    $query->range(0, $limit);
  }

  // Execute the query and build the results array.
  $result = $query->execute();

  $matches = array();

  foreach ($result->fetchAll() as $store) {
    $matches[$store->store_id] = array(
      'title' => $store->title,
      'rendered' => t('@title', array('@title' => $store->title)),
    );
  }

  return $matches;
}

/**
 * Access callback: determines access to a store's translation tab.
 */
function commerce_store_entity_translation_tab_access($store) {
  if (!empty($store->language) && $store->language != LANGUAGE_NONE) {
    if (commerce_store_entity_translation_supported_type($store->type)) {
      return entity_translation_tab_access('commerce_store');
    }
  }

  return FALSE;
}

/**
 * Returns whether the given store type has support for translations.
 *
 * @param $type
 *   The machine-name of the store type to check for translation support.
 *
 * @return
 *   TRUE or FALSE indicating translation support for the requested type.
 */
function commerce_store_entity_translation_supported_type($type) {
  return variable_get('language_store_type_' . $type, 0) == ENTITY_TRANSLATION_ENABLED;
}

/**
 * Sanitizes the store title before output.
 */
function template_preprocess_commerce_store_title(&$variables) {
  $variables['title'] = check_plain($variables['title']);
}

/**
 * Converts the store status integer to a string before output.
 */
function template_preprocess_commerce_store_status(&$variables) {
  $variables['status'] = empty($variables['status']) ? t('Disabled') : t('Active');
}

/**
 * Returns an initialized store object.
 *
 * @param $uid
 *   The uid of the owner of the store.
 * @param $status
 *   Optionally the status of the new store.
 *
 * @return
 *   A store object with all default fields initialized.
 */
function commerce_store_new($uid = 0, $status = NULL, $type = 'commerce_store') {
  // If no status was specified, use the default disabled status.
  if (!isset($status)) {
    $status = 0;
  }

  return entity_get_controller('commerce_store')->create(array(
    'title' => '',
    'uid' => $uid,
    'status' => $status,
  ));
}
