<?php

/**
 * @file
 */

/**
 * Implements hook_menu().
 */
function commerce_store_ui_menu() {
  $items = array();

  // Note: admin/commerce/stores is defined by a default View.

  // Add a store.
  $items['admin/commerce/stores/add'] = array(
    'title' => 'Add a store',
    'description' => 'Add a new store.',
    'page callback' => 'commerce_store_ui_store_form_wrapper',
    'page arguments' => array(commerce_store_new()),
    'access callback' => 'commerce_store_ui_store_add_any_access',
    'weight' => 10,
    'file' => 'includes/commerce_store_ui.stores.inc',
  );

  $items['admin/commerce/stores/%commerce_store'] = array(
    'title callback' => 'commerce_store_ui_store_title',
    'title arguments' => array(3),
    'page callback' => 'commerce_store_ui_store_form_wrapper',
    'page arguments' => array(3),
    'access callback' => 'commerce_store_access',
    'access arguments' => array('update', 3),
    'weight' => 0,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'file' => 'includes/commerce_store_ui.stores.inc',
  );

  $items['admin/commerce/stores/%commerce_store/edit'] = array(
    'title' => 'Edit',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );

  $items['admin/commerce/stores/%commerce_store/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'commerce_store_ui_store_delete_form_wrapper',
    'page arguments' => array(3),
    'access callback' => 'commerce_store_access',
    'access arguments' => array('update', 3),
    'type' => MENU_LOCAL_TASK,
    'weight' => 20,
    'context' => MENU_CONTEXT_INLINE,
    'file' => 'includes/commerce_store_ui.stores.inc',
  );

  return $items;
}

/**
 * Menu item title callback: returns the SKU of a store for its pages.
 *
 * @param $store
 *   The store object as loaded via the URL wildcard.
 * @return
 *   A page title of the format "Store: [Title]".
 */
function commerce_store_ui_store_title($store) {
  return t('Store: @title', array('@title' => $store->title));
}

/**
 * Access callback: determines if the user can create any type of store.
 */
function commerce_store_ui_store_add_any_access() {
  // Grant automatic access to users with administer stores permission.
  if (user_access('administer commerce_store entities')) {
    return TRUE;
  }

  return FALSE;
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function commerce_store_ui_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  // Add action link 'admin/commerce/stores/add' on 'admin/commerce/stores'.
  if ($root_path == 'admin/commerce/stores') {
    $item = menu_get_item('admin/commerce/stores/add');
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }
}

/**
 * Implements hook_theme().
 */
function commerce_store_ui_theme() {
  return array(
    'store_add_list' => array(
      'variables' => array('content' => array()),
      'file' => 'includes/commerce_store_ui.stores.inc',
    ),
  );
}

/**
 * Implements hook_entity_info_alter().
 */
function commerce_store_ui_entity_info_alter(&$entity_info) {
  // Add a URI callback to the store entity.
  $entity_info['commerce_store']['uri callback'] = 'commerce_store_ui_store_uri';
}

/**
 * Entity uri callback: points to the edit form of the given store if no other
 *   URI is specified.
 */
function commerce_store_ui_store_uri($store) {
  // First look for a return value in the default entity uri callback.
  $uri = commerce_store_uri($store);

  // If a value was found, return it now.
  if (!empty($uri)) {
    return $uri;
  }

  // Otherwise return an admin URI if the user has permission.
  if (commerce_store_access('view', $store)) {
    return array(
      'path' => 'admin/commerce/stores/' . $store->store_id,
    );
  }

  return NULL;
}

/**
 * Implements hook_forms().
 */
function commerce_store_ui_forms($form_id, $args) {
  $forms = array();

  // Define a wrapper ID for the store add / edit form.
  $forms['commerce_store_ui_store_form'] = array(
    'callback' => 'commerce_store_store_form',
  );

  // Define a wrapper ID for the store delete confirmation form.
  $forms['commerce_store_ui_store_delete_form'] = array(
    'callback' => 'commerce_store_store_delete_form',
  );

  return $forms;
}

/**
 * Implements hook_form_alter().
 */
function commerce_store_ui_form_alter(&$form, &$form_state, $form_id) {
  // On field administration forms for store types add a breadcrumb.
  if (in_array($form_id, array('field_ui_field_overview_form', 'field_ui_display_overview_form'))) {
    if ($form['#entity_type'] == 'commerce_store') {
      commerce_store_ui_set_breadcrumb(TRUE);
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * The Store UI module instantiates the Store add/edit form at particular
 * paths in the Commerce IA. It uses its own form ID to do so and alters the
 * form here to add in appropriate redirection and an additional button.
 *
 * @see commerce_store_ui_store_form()
 */
function commerce_store_ui_form_commerce_store_ui_store_form_alter(&$form, &$form_state) {
  $store = $form_state['commerce_store'];

  // Add a submit handler to the save button to add a redirect.
  $form['actions']['submit']['#submit'][] = 'commerce_store_ui_store_form_submit';

  // If translation support is enabled, provide the suitable languages
  if (module_exists('entity_translation') && entity_translation_enabled('commerce_store')) {
    $handler = entity_translation_get_handler('commerce_store', $store);
    $translations = $handler->getTranslations();

    $form['language'] = array(
      '#type' => 'select',
      '#title' => t('Language'),
      '#default_value' => isset($store->language) ? $store->language : '',
      '#options' => array(LANGUAGE_NONE => t('Language neutral')) + locale_language_list('name'),
      '#weight' => -10,
    );

    // Disable languages for existing translations, so it is not possible to
    // switch this store to some language which is already in the translation set.
    foreach ($translations->data as $langcode => $translation) {
      if ($langcode != $translations->original) {
        unset($form['language']['#options'][$langcode]);
      }
    }

    // Since this function may change the language of the submitted form values,
    // it has to be the first called.
    array_unshift($form['actions']['submit']['#submit'], 'commerce_store_ui_store_form_translation_submit');
  }

  // Add the save and continue button for new stores.
  if (empty($store->store_id)) {
    $form['actions']['save_continue'] = array(
      '#type' => 'submit',
      '#value' => t('Save and add another'),
      '#submit' => $form['actions']['submit']['#submit'],
      '#suffix' => l(t('Cancel'), 'admin/commerce/stores'),
      '#weight' => 45,
    );
  }
  else {
    $form['actions']['submit']['#suffix'] = l(t('Cancel'), 'admin/commerce/stores');
  }
}

/**
 * Submit callback for commerce_store_ui_store_form().
 *
 * @see commerce_store_ui_form_commerce_store_ui_store_form_alter()
 */
function commerce_store_ui_store_form_submit($form, &$form_state) {
  // Set the redirect based on the button clicked.
  $array_parents = $form_state['triggering_element']['#array_parents'];
  $submit_element = array_pop($array_parents);

  if (arg(2) == 'stores' && arg(3) == 'add') {
    $form_state['redirect'] = 'admin/commerce/stores';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * The Store UI module instantiates the Store delete form at a particular
 * path in the Commerce IA. It uses its own form ID to do so and alters the
 * form here to add in appropriate redirection.
 *
 * @see commerce_store_ui_store_delete_form()
 */
function commerce_store_ui_form_commerce_store_ui_store_delete_form_alter(&$form, &$form_state) {
  $form['actions']['cancel']['#href'] = 'admin/commerce/stores';
  $form['#submit'][] = 'commerce_store_ui_store_delete_form_submit';
}

/**
 * Submit callback for commerce_store_ui_store_delete_form().
 *
 * @see commerce_store_ui_form_commerce_store_ui_store_delete_form_alter()
 */
function commerce_store_ui_store_delete_form_submit($form, &$form_state) {
  $form_state['redirect'] = 'admin/commerce/stores';
}

/**
 * Implements hook_views_api().
 */
function commerce_store_ui_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'commerce_store_ui') . '/includes/views',
  );
}

/**
 * Sets the breadcrumb for administrative store pages.
 *
 * @param $store_types
 *   TRUE or FALSE indicating whether or not the breadcrumb should include the
 *     store types administrative page.
 *
 * @deprecated since 7.x-1.4
 */
function commerce_store_ui_set_breadcrumb($store_types = FALSE) {
}
