<?php

/**
 * @file
 */

/**
 * Implements hook_menu().
 */
function commerce_seller_ui_menu() {
  $items = array();

  // Note: admin/commerce/seller-profiles is defined by a default View.

  // Add a seller profile.
  $items['admin/commerce/seller-profiles/add'] = array(
    'title' => 'Add a seller profile',
    'description' => 'Add a new seller profile.',
    'page callback' => 'commerce_seller_ui_seller_profile_add_page',
    'access callback' => 'commerce_seller_ui_seller_profile_add_any_access',
    'weight' => 10,
    'file' => 'includes/commerce_seller_ui.profiles.inc',
  );

  $items['admin/commerce/seller-profiles/%commerce_seller_profile'] = array(
    'title callback' => 'commerce_seller_ui_seller_profile_title',
    'title arguments' => array(3),
    'page callback' => 'commerce_seller_ui_seller_profile_form_wrapper',
    'page arguments' => array(3),
    'access callback' => 'commerce_seller_profile_access',
    'access arguments' => array('update', 3),
    'weight' => 0,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'file' => 'includes/commerce_seller_ui.profiles.inc',
  );
  $items['admin/commerce/seller-profiles/%commerce_seller_profile/edit'] = array(
    'title' => 'Edit',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );
  $items['admin/commerce/seller-profiles/%commerce_seller_profile/delete'] = array(
    'title' => 'Delete a seller profile',
    'page callback' => 'commerce_seller_ui_seller_profile_delete_form_wrapper',
    'page arguments' => array(3),
    'access callback' => 'commerce_seller_profile_access',
    'access arguments' => array('delete', 3),
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
    'context' => MENU_CONTEXT_INLINE,
    'file' => 'includes/commerce_seller_ui.profiles.inc',
  );

  return $items;
}

/**
 * Menu item title callback: returns the ID of a seller profile for its pages.
 *
 * @param $profile
 *   The seller profile object as loaded via the URL wildcard.
 * @return
 *   A page title of the format "Profile [profile-id]".
 */
function commerce_seller_ui_seller_profile_title($profile) {
  return t('seller profile @profile_id', array('@profile_id' => $profile->profile_id));
}

/**
 * Access callback: determine if the user can create any type of profile.
 */
function commerce_seller_ui_seller_profile_add_any_access() {
  // Grant automatic access to users with administer seller profiles permission.
  if (user_access('administer commerce_seller_profile entities')) {
    return TRUE;
  }

  return FALSE;
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function commerce_seller_ui_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  // Add action link 'admin/commerce/seller-profiles/add' on
  // 'admin/commerce/seller-profiles'.
  if ($root_path == 'admin/commerce/seller-profiles') {
    $item = menu_get_item('admin/commerce/seller-profiles/add');
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }
}


/**
 * Implements hook_theme().
 */
function commerce_seller_ui_theme() {
  return array(
    'seller_profile_add_list' => array(
      'variables' => array('content' => array()),
      'file' => 'includes/commerce_seller_ui.profiles.inc',
    ),
    'commerce_seller_profile_status' => array(
      'variables' => array('status' => NULL, 'label' => NULL, 'profile' => NULL),
      'path' => drupal_get_path('module', 'commerce_seller_ui') . '/theme',
      'template' => 'commerce-seller-profile-status',
    ),
  );
}

/**
 * Implements hook_entity_info_alter().
 */
function commerce_seller_ui_entity_info_alter(&$entity_info) {
  // Add a URI callback to the profile entity.
  $entity_info['commerce_seller_profile']['uri callback'] = 'commerce_seller_ui_seller_profile_uri';
}

/**
 * Entity uri callback: points to the edit form of the given profile.
 */
function commerce_seller_ui_seller_profile_uri($profile) {
  // First look for a return value in the default entity uri callback.
  $uri = commerce_seller_profile_uri($profile);

  // If a value was found, return it now.
  if (!empty($uri)) {
    return $uri;
  }

  // Only return a value if the user has permission to view the profile.
  if (commerce_seller_profile_access('view', $profile)) {
    return array(
      'path' => 'admin/commerce/seller-profiles/' . $profile->profile_id,
    );
  }

  return NULL;
}

/**
 * Implements hook_forms().
 */
function commerce_seller_ui_forms($form_id, $args) {
  $forms = array();

  // Define a wrapper ID for the seller profile add / edit form.
  $forms['commerce_seller_ui_seller_profile_form'] = array(
    'callback' => 'commerce_seller_seller_profile_form',
  );

  // Define a wrapper ID for the seller profile delete confirmation form.
  $forms['commerce_seller_ui_seller_profile_delete_form'] = array(
    'callback' => 'commerce_seller_seller_profile_delete_form',
  );

  return $forms;
}

/**
 * Implements hook_form_alter().
 */
function commerce_seller_ui_form_alter(&$form, &$form_state, $form_id) seller

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * The seller UI module instantiates the Profile add/edit form at particular
 * paths in the Commerce IA. It uses its own form ID to do so and alters the
 * form here to add in appropriate redirection and an additional button.
 *
 * @see commerce_seller_ui_seller_profile_form()
 */
function commerce_seller_ui_form_commerce_seller_ui_seller_profile_form_alter(&$form, &$form_state) {
  // Add a submit handler to the save button to add a redirect.
  $form['actions']['submit']['#submit'][] = 'commerce_seller_ui_seller_profile_form_submit';

  // Add the save and continue button for new profiles.
  if (empty($form_state['seller_profile']->profile_id)) {
    $form['actions']['save_continue'] = array(
      '#type' => 'submit',
      '#value' => t('Save and add another'),
      '#submit' => $form['actions']['submit']['#submit'],
      '#suffix' => l(t('Cancel'), 'admin/commerce/seller-profiles'),
      '#weight' => 45,
    );
  }
  else {
    $form['actions']['submit']['#suffix'] = l(t('Cancel'), 'admin/commerce/seller-profiles');
  }
}

/**
 * Submit callback for commerce_seller_ui_seller_profile_form().
 *
 * @see commerce_seller_ui_form_commerce_seller_ui_seller_profile_form_alter()
 */
function commerce_seller_ui_seller_profile_form_submit($form, &$form_state) {
  // Set the redirect based on the button clicked.
  if ($form_state['triggering_element']['#parents'][0] == 'save_continue') seller
  elseif (arg(2) == 'seller-profiles' && arg(3) == 'add') {
    $form_state['redirect'] = 'admin/commerce/seller-profiles';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * The seller UI module instantiates the Profile delete form at a particular
 * path in the Commerce IA. It uses its own form ID to do so and alters the
 * form here to add in appropriate redirection.
 *
 * @see commerce_seller_ui_seller_profile_delete_form()
 */
function commerce_seller_ui_form_commerce_seller_ui_seller_profile_delete_form_alter(&$form, &$form_state) {
  $form['actions']['cancel']['#href'] = 'admin/commerce/seller-profiles';
  $form['#submit'][] = 'commerce_seller_ui_seller_profile_delete_form_submit';
}

/**
 * Submit callback for commerce_seller_ui_seller_profile_delete_form().
 *
 * @see commerce_seller_ui_form_commerce_seller_ui_seller_profile_delete_form_alter()
 */
function commerce_seller_ui_seller_profile_delete_form_submit($form, &$form_state) {
  $form_state['redirect'] = 'admin/commerce/seller-profiles';
}

/**
 * Implements hook_views_api().
 */
function commerce_seller_ui_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'commerce_seller_ui') . '/includes/views',
  );
}

/**
 * Sets the breadcrumb for administrative seller pages.
 *
 * @param $profiles
 *   TRUE or FALSE indicating whether or not the breadcrumb should include the
 *     profiles overview page.
 * @param $profile_types
 *   TRUE or FALSE indicating whether or not the breadcrumb should include the
 *     profile types administrative page.
 *
 * @deprecated since 7.x-1.4
 */
function commerce_seller_ui_set_breadcrumb($profile_types = FALSE) {
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function commerce_seller_ui_form_entity_translation_admin_form_alter(&$form, &$form_state, $form_id) {
  // Hide the commerce_seller_profile option from entity translation.
  unset($form['entity_translation_entity_types']['#options']['commerce_seller_profile']);
}
